# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

# Grid
X_GRID = 300
Y_GRID = X_GRID
TILESIZE = min(SCREEN_WIDTH / X_GRID, SCREEN_HEIGHT / Y_GRID)
GRID_COLOR = (50, 0, 0)

# Color
SCREEN_COLOR = (0, 0, 0)