# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

# Grid
X_GRID = 300
Y_GRID = X_GRID
TILESIZE = min(SCREEN_WIDTH / X_GRID, SCREEN_HEIGHT / Y_GRID)
GRID_COLOR = (50, 0, 0)

# Prey
PREY_INITIAL_COUNT = 100
PREY_SPAWN_RATE = 5
PREY_COLOR = (0, 150, 0)

# Color
SCREEN_COLOR = (0, 0, 0)
PREY_COLOR = (0, 255, 0)